### ISSUE TITLE
Remove comment about Live Photos will loose its videos

### ISSUE THREAD

**Issue by timaschew** [joojoooo/immich-upload-optimizer#1]
Server: 1.129.0
I'm using the lossy setup:

```
  - name: heic-to-avif
    #command: ./convert-heic.sh 70 "{{.folder}}" "{{.name}}" "{{.extension}}" "{{.result_folder}}"
    command: ./convert.sh "{{.folder}}" "{{.name}}" "{{.extension}}" "{{.result_folder}}" avif
    extensions:
      - heic
      - heif
```
Live Photos do work with videos like without the IUO.
In the web the element shows a play button with a dot in the corner. If I open it, and click on download I get two files:

- IMG_9359.avif - 891 KB
- IMG_9359.MOV - 2.3 MB

I've created another user and logged in via the other IP without IUO and upload the same live photo, same result in the web, when downloading the files I get this:

- IMG_9359.avif - 1.9 MB
- IMG_9359.MOV - 5.9 MB
