### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by jvital-stonify** [joojoooo/immich-upload-optimizer#7]
I had a problem where if I download from immich web app, the download file comes with 0bytes.

From the console I get:
`The file at 'blob:http://immich-server:2284/id' was loaded over an insecure connection. This file should be served over HTTPS.
`
I don't know if this is an error or just a warning.

**Comment by joojoooo** [comment]
where are you reading this log from? Is it by IUO ?

**Comment by joojoooo** [comment]
looks like it's your browser issue, neither immich nor IUO use HTTPS, if you want HTTPS you do so with proxies like nginx.

Are you using http or https to the website? what proxy are you using? are you using jxl/avif to JPEG conversion ? what's the IUO logs?

**Comment by joojoooo** [comment]
> I don't know if this is an error or just a warning

It's a browser error that prevents you from downloading and unless you give more info, seems unrelated to IUO or immich.

**Comment by jvital-stonify** [comment]
The relevant logs logs from IUO
2025/04/18 20:29:01 172.18.0.1: request URL: /api/assets/469df2d4-5646-4054-95ba-6559753a302b/original
2025/04/18 20:29:01 172.18.0.1: converting to jpg: /api/assets/469df2d4-5646-4054-95ba-6559753a302b/original

I'm not using any proxy, I'm on my LAN, serving immich from my NAS, accessing on http://immich-server:2284. I'm using Edge as browser, already tried chrome with the same result. 

I will try to stop the services  and run it without IUO.

**Comment by jvital-stonify** [comment]
I already tried to change page permissions to allow all (automatic downloads, insecure content, etc), without success

**Comment by joojoooo** [comment]
> The relevant logs logs from IUO

that's not the full log, you should also see the output of avifdec/djxl , is the conversion successful? is the file avif or jxl? if unsuccessful can you send the file?

> I will try to stop the services and run it without IUO.

If you're using the default docker compose you can already access immich directly on port 2283, check if the download works when downloading directly from immich

**Comment by jvital-stonify** [comment]
Running immich the files download.
So the blob is just a warning, not an error.

So now I don't now if there is any error with my IUO setup.

this is my YAML

```
services:
  immich-upload-optimizer:
   image: ghcr.io/joojoooo/immich-upload-optimizer:latest
   tmpfs:
     - /tempfs
   ports:
    - "2284:2284"
   environment:
    - IUO_UPSTREAM=http://immich-server:2283
    - IUO_LISTEN=:2284
    - IUO_TASKS_FILE=/etc/immich-upload-optimizer/config/lossless/lossless_jxl.yaml
    - IUO_CHECKSUMS_FILE=/IUO/checksums.csv # Uncomment after defining a volume
    - TMPDIR=/tempfs # Writes uploaded files in RAM to improve disk lifespan (Remove if running low on RAM)
    - IUO_DOWNLOAD_JPG_FROM_JXL=true # Uncomment to enable JXL to JPG conversion
      #- IUO_DOWNLOAD_JPG_FROM_AVIF=true # Uncomment to enable AVIF to JPG conversion
   volumes:
     - /volume1/docker/immich-app/optimizer/config:/etc/immich-upload-optimizer/config
     #- /volume1/docker/immich-app:/IUO # Keep the checksums and tasks files between updates by defining a volume
   restart: always
   depends_on:
    - immich-server
 
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /volume1/photo:/mnt/photo
    env_file:
      - .env
    #ports:
      #- '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
```
